import { Resend } from 'resend'
import { escHtml as esc, escSubject } from './email-utils'

const from = () => process.env.EMAIL_FROM || 'onboarding@resend.dev'

export async function sendPayslipEmail({
  to, employeeName, employerName, payslipNumber, netPay, payPeriod, pdfBase64, logoUrl,
}: {
  to: string
  employeeName: string
  employerName: string
  payslipNumber: string
  netPay: string
  payPeriod: string
  pdfBase64: string
  logoUrl?: string
}): Promise<void> {
  const resend  = new Resend(process.env.RESEND_API_KEY)
  const safeLogo = logoUrl && logoUrl.startsWith('https://') ? logoUrl : ''
  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)">
        <tr>
          <td style="background:#1C1917;padding:28px 36px">
            ${safeLogo ? `<img src="${safeLogo}" alt="${esc(employerName)}" style="max-height:60px;max-width:200px;object-fit:contain;margin-bottom:8px;display:block;" />` : ''}
            <p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${esc(employerName || 'Your Employer')}</p>
            <p style="margin:6px 0 0;color:#A09590;font-size:13px">Payslip Notification</p>
          </td>
        </tr>
        <tr>
          <td style="padding:36px">
            <p style="margin:0 0 8px;color:#1C1917;font-size:15px">Hi ${esc(employeeName)},</p>
            <p style="margin:0 0 28px;color:#57534E;font-size:14px;line-height:1.6">
              Your payslip for <strong>${esc(payPeriod)}</strong> is ready. Please find it attached to this email.
            </p>
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px">
              <tr><td style="padding:20px 24px">
                <table width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">Payslip Number</td>
                    <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(payslipNumber)}</td>
                  </tr>
                  <tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">Pay Period</td>
                    <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(payPeriod)}</td>
                  </tr>
                  <tr>
                    <td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Net Pay</td>
                    <td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${esc(netPay)}</td>
                  </tr>
                </table>
              </td></tr>
            </table>
            <p style="margin:0 0 6px;color:#57534E;font-size:13px;line-height:1.6">
              If you have any questions about your payslip, please contact your employer directly.
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5">
            <p style="margin:0;color:#A09590;font-size:11px;text-align:center">
              Generated by SAB Account AI · ATO-compliant PAYG withholding
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`

  const { error } = await resend.emails.send({
    from: from(),
    to:   [to],
    subject: `Your payslip ${escSubject(payslipNumber)} from ${escSubject(employerName)}`,
    html,
    attachments: [{ filename: `${payslipNumber}.pdf`, content: pdfBase64 }],
  })
  if (error) throw new Error((error as { message?: string }).message ?? 'Failed to send email')
}

export async function sendInvoiceEmail({
  to, clientName, businessName, invoiceNumber, totalDue, dueDate, pdfBase64, logoUrl, clientAbn, totalIncGst,
}: {
  to: string
  clientName: string
  businessName: string
  invoiceNumber: string
  totalDue: string
  dueDate: string
  pdfBase64: string
  logoUrl?: string
  clientAbn?: string
  totalIncGst?: number
}): Promise<void> {
  const resend   = new Resend(process.env.RESEND_API_KEY)
  const safeLogo = logoUrl && logoUrl.startsWith('https://') ? logoUrl : ''
  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)">
        <tr>
          <td style="background:#1C1917;padding:28px 36px">
            ${safeLogo ? `<img src="${safeLogo}" alt="${esc(businessName)}" style="max-height:60px;max-width:200px;object-fit:contain;margin-bottom:8px;display:block;" />` : ''}
            <p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${esc(businessName || 'Your Supplier')}</p>
            <p style="margin:6px 0 0;color:#A09590;font-size:13px">Tax Invoice</p>
          </td>
        </tr>
        <tr>
          <td style="padding:36px">
            <p style="margin:0 0 8px;color:#1C1917;font-size:15px">Hi ${esc(clientName)},</p>
            <p style="margin:0 0 28px;color:#57534E;font-size:14px;line-height:1.6">
              Please find your invoice <strong>${esc(invoiceNumber)}</strong> from <strong>${esc(businessName)}</strong> attached to this email.
            </p>
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px">
              <tr><td style="padding:20px 24px">
                <table width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">Invoice Number</td>
                    <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(invoiceNumber)}</td>
                  </tr>
                  <tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">Due Date</td>
                    <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(dueDate)}</td>
                  </tr>
                  ${clientAbn ? `<tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">Your ABN</td>
                    <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(clientAbn)}</td>
                  </tr>` : ''}
                  <tr>
                    <td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Total Due (inc GST)</td>
                    <td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${esc(totalDue)}</td>
                  </tr>
                </table>
              </td></tr>
            </table>
            ${!clientAbn && (totalIncGst ?? 0) >= 1000 ? `<p style="margin:0 0 16px;color:#92400E;font-size:12px;line-height:1.5;background:#FEF3C7;border-radius:6px;padding:10px 14px">
              Please provide your ABN to ${esc(businessName)} for invoices over $1,000 (ATO requirement).
            </p>` : ''}
            <p style="margin:0 0 6px;color:#57534E;font-size:13px;line-height:1.6">
              Please reference the invoice number when making payment. If you have any questions, reply to this email or contact ${esc(businessName)} directly.
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5">
            <p style="margin:0;color:#A09590;font-size:11px;text-align:center">
              Generated by SAB Account AI
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`

  const { error } = await resend.emails.send({
    from: from(),
    to:   [to],
    subject: `Invoice ${escSubject(invoiceNumber)} from ${escSubject(businessName)} — ${totalDue} due ${dueDate}`,
    html,
    attachments: [{ filename: `${invoiceNumber}.pdf`, content: pdfBase64 }],
  })
  if (error) throw new Error((error as { message?: string }).message ?? 'Failed to send email')
}
