import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import * as Sentry from '@sentry/nextjs'
import { createServiceClient } from '@/lib/supabase'
import { escHtml as esc, escSubject } from '@/lib/email-utils'

export async function POST(req: NextRequest) {
  const resend = new Resend(process.env.RESEND_API_KEY)
  const token = req.headers.get('Authorization')?.replace('Bearer ', '')
  if (!token) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const supabase = createServiceClient()
  const { data: { user }, error: authErr } = await supabase.auth.getUser(token)
  if (authErr || !user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const { to, businessName, quarter, basDue, netGST, paygWithheld, pdfBase64 } =
    await req.json() as {
      to: string
      businessName: string
      quarter: string
      basDue: string
      netGST: number
      paygWithheld: number
      pdfBase64: string
    }

  if (!to || !pdfBase64) return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  if (pdfBase64.length > 5_000_000) return NextResponse.json({ error: 'PDF too large' }, { status: 400 })

  const fc = (n: number) => '$' + Math.abs(n).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)">

        <tr>
          <td style="background:#1C1917;padding:28px 36px">
            <p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${esc(businessName || 'SAB Account AI')}</p>
            <p style="margin:6px 0 0;color:#A09590;font-size:13px">BAS Summary — ${esc(quarter)}</p>
          </td>
        </tr>

        <tr>
          <td style="padding:36px">
            <p style="margin:0 0 20px;color:#57534E;font-size:14px;line-height:1.6">
              Please find attached the Business Activity Statement summary for <strong>${esc(quarter)}</strong>.
              The figures below are drawn from ${esc(businessName || 'the business')}'s records in SAB Account AI.
            </p>

            <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px">
              <tr><td style="padding:20px 24px">
                <table width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">Quarter</td>
                    <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(quarter)}</td>
                  </tr>
                  <tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">BAS Due Date</td>
                    <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(basDue)}</td>
                  </tr>
                  <tr>
                    <td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Net GST to Pay ATO</td>
                    <td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${fc(netGST)}</td>
                  </tr>
                  ${paygWithheld > 0 ? `
                  <tr>
                    <td style="padding:6px 0;color:#78716C;font-size:13px">PAYG Withholding (W2)</td>
                    <td align="right" style="padding:6px 0;color:#C84B2F;font-size:13px;font-weight:600">${fc(paygWithheld)}</td>
                  </tr>` : ''}
                </table>
              </td></tr>
            </table>

            <p style="margin:0 0 6px;color:#57534E;font-size:13px;line-height:1.6">
              The full BAS summary PDF is attached. Please use the figures in the PDF to lodge via the ATO Business Portal or myGov.
            </p>
            <p style="margin:0;color:#A09590;font-size:12px;line-height:1.6">
              This summary is generated from invoices and expense records in SAB Account AI and is for reference only. It is not a lodgement document.
            </p>
          </td>
        </tr>

        <tr>
          <td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5">
            <p style="margin:0;color:#A09590;font-size:11px;text-align:center">
              Generated by SAB Account AI · sabaccountai.com · ATO-compliant GST &amp; PAYG figures
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`

  const filename = `BAS-Summary-${quarter.replace(/\s/g, '-')}.pdf`

  const { error } = await resend.emails.send({
    from: process.env.EMAIL_FROM || 'onboarding@resend.dev',
    to: [to],
    subject: `BAS Summary ${escSubject(quarter)} — ${escSubject(businessName)}`,
    html,
    attachments: [{ filename, content: pdfBase64 }],
  })

  if (error) {
    Sentry.captureException(new Error((error as { message?: string }).message ?? 'Resend failed'), { tags: { feature: 'email_send', type: 'bas' } })
    return NextResponse.json({ error: (error as { message?: string }).message ?? 'Failed to send email' }, { status: 500 })
  }

  return NextResponse.json({ ok: true })
}
