import { SupabaseClient } from '@supabase/supabase-js'
import { Resend } from 'resend'
import * as Sentry from '@sentry/nextjs'
import { calculatePayslip, isMedicareExemptByResidency } from '@/lib/ato'
import { formatABN } from '@/lib/utils'
import PDFDocument from 'pdfkit'
import { getPayslipPDFBase64, getInvoicePDFBase64 } from '@/lib/pdf'

// ── Generate BAS PDF as a Buffer ──────────────────────────────────────
async function generateBasPdf(data: {
  businessName: string
  abn: string
  period: string
  totalIncome: number
  gstCollected: number
  totalExpenses: number
  gstCredits: number
  netGst: number
  paygWithheld: number
  invoices: Array<{ invoice_number: string; client_name: string; issue_date: string; total_inc_gst: number; total_gst: number }>
  generatedDate: string
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' })
    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const DARK   = '#1C1917'
    const MID    = '#57534E'
    const LIGHT  = '#A09590'
    const RED    = '#C84B2F'
    const BORDER = '#E5DDD5'
    const BG     = '#F5F0E8'

    const pageW  = doc.page.width  - 100
    const fmtN   = (n: number) => `$${Math.abs(n).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`

    // ── Header bar ────────────────────────────────────────────────
    doc.rect(50, 50, pageW, 70).fill(DARK)
    doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(16).text(data.businessName, 70, 65)
    doc.fillColor(LIGHT).font('Helvetica').fontSize(10)
      .text(`BAS Summary — ${data.period}`, 70, 87)
      .text(data.abn ? `ABN: ${data.abn}` : '', 70, 102)

    // ── Summary box ───────────────────────────────────────────────
    let y = 140
    doc.rect(50, y, pageW, 160).fill(BG)

    const col1 = 70
    const col2 = 370
    y += 16

    const row = (label: string, value: string, bold = false, color = DARK) => {
      doc.fillColor(MID).font('Helvetica').fontSize(10).text(label, col1, y)
      doc.fillColor(color).font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(bold ? 12 : 10)
        .text(value, col2, y, { align: 'right', width: pageW - col2 + 50 })
      y += 20
    }

    row('Total Income (inc. GST)', fmtN(data.totalIncome))
    row('GST Collected on Sales (1A)', fmtN(data.gstCollected))
    y += 4
    doc.moveTo(col1, y).lineTo(col1 + pageW - 20, y).strokeColor(BORDER).lineWidth(0.5).stroke()
    y += 8
    row('Total Expenses (inc. GST)', fmtN(data.totalExpenses))
    row('GST Credits on Purchases (1B)', fmtN(data.gstCredits))
    y += 4
    doc.moveTo(col1, y).lineTo(col1 + pageW - 20, y).strokeColor(BORDER).lineWidth(0.5).stroke()
    y += 8

    const netLabel = data.netGst >= 0 ? 'Net GST Payable to ATO' : 'GST Refund from ATO'
    row(netLabel, fmtN(data.netGst), true, data.netGst >= 0 ? RED : DARK)

    if (data.paygWithheld > 0) {
      y += 4
      doc.moveTo(col1, y).lineTo(col1 + pageW - 20, y).strokeColor(BORDER).lineWidth(0.5).stroke()
      y += 8
      row('PAYG Withholding from Employees (W2)', fmtN(data.paygWithheld))
      const totalPayable = data.netGst + data.paygWithheld
      row('Total Amount Payable to ATO', fmtN(totalPayable), true, RED)
    }

    // ── Invoice list ──────────────────────────────────────────────
    if (data.invoices.length > 0) {
      y += 20
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(11).text('Invoices', 50, y)
      y += 16

      // Table header
      doc.rect(50, y, pageW, 18).fill(DARK)
      doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(8)
        .text('NUMBER',    70,  y + 5)
        .text('CLIENT',    145, y + 5)
        .text('DATE',      330, y + 5)
        .text('TOTAL',     405, y + 5)
        .text('GST',       470, y + 5)
      y += 18

      data.invoices.forEach((inv, i) => {
        if (i % 2 === 0) doc.rect(50, y, pageW, 18).fill(BG)
        doc.fillColor(MID).font('Helvetica').fontSize(8)
          .text(inv.invoice_number,                70,  y + 5, { width: 70 })
          .text(inv.client_name,                   145, y + 5, { width: 180 })
          .text(inv.issue_date,                    330, y + 5, { width: 70 })
          .text(fmtN(inv.total_inc_gst),           405, y + 5, { width: 60 })
          .text(fmtN(inv.total_gst),               470, y + 5, { width: 60 })
        y += 18
        if (y > doc.page.height - 80) { doc.addPage(); y = 50 }
      })
    }

    // ── Footer ────────────────────────────────────────────────────
    y = doc.page.height - 60
    doc.moveTo(50, y).lineTo(50 + pageW, y).strokeColor(BORDER).lineWidth(0.5).stroke()
    doc.fillColor(LIGHT).font('Helvetica').fontSize(8)
      .text(`Generated by SAB Account AI · sabaccountai.com · ${data.generatedDate}`, 50, y + 10, { align: 'center', width: pageW })

    doc.end()
  })
}

// ── REPLACED: invoice PDF now uses getInvoicePDFBase64 from @/lib/pdf ──
// (jsPDF gold standard — identical output to the UI invoice builder)

// ── REPLACED: payslip PDF now uses getPayslipPDFBase64 from @/lib/pdf ──
// (jsPDF gold standard — identical output to the UI payslip wizard)


// ── ATO static knowledge ──────────────────────────────────────────────
const ATO_RULES: Record<string, string> = {
  super: `Super Guarantee (SG) rates:
- FY2024-25: 11.5%
- FY2025-26: 12.0% (from 1 July 2025)
- Future: stays at 12% (no further scheduled increases as of 2026)
Super must be paid into a complying fund or the employee's chosen fund.
Payday Super from 1 July 2026: super must be paid on every payday, not quarterly.
Late super attracts a Superannuation Guarantee Charge (SGC) which is non-deductible.`,

  medicare: `Medicare Levy: 2% of taxable income for Australian residents.
Exemptions (no Medicare levy):
- International students (student visa)
- Temporary work visa holders (482, 457, 400 etc)
- Working Holiday Makers (417, 462)
- Partner/dependent visas (temporary)
- Other temporary residents
Low-income threshold 2025-26: $27,222 (no levy below this). Phase-in between $27,222 and $34,028.
HELP/HECS repayment is separate from Medicare and applies from $67,000 income.`,

  payg: `PAYG Withholding scales (NAT 1004, FY2025-26):
Scale 1: Employee has NOT claimed tax-free threshold. No LITO. Higher withholding from first dollar. Used for second jobs.
Scale 2: Employee HAS claimed tax-free threshold. Includes Medicare and LITO phaseout. Primary scale for Australian residents.
Scale 3: Foreign residents. No Medicare, no LITO, no tax-free threshold.
Scale 5: Claiming threshold + FULL Medicare levy exemption. No Medicare withheld. For temp residents/international students who claim threshold.
WHM (Schedule 15): Working holiday makers. 15% up to $45,000, 30% up to $135,000, 37% up to $190,000, 45% above.
All PAYG amounts are rounded to the nearest dollar per ATO rules.`,

  bas: `BAS (Business Activity Statement) due dates for quarterly lodgers:
- Q1 (Jul-Sep): due 28 October
- Q2 (Oct-Dec): due 28 February
- Q3 (Jan-Mar): due 28 April
- Q4 (Apr-Jun): due 28 July
Monthly BAS lodgers: due 21st of the following month.
GST rate: 10% on taxable supplies. Input tax credits (ITCs) offset GST collected.
Net GST = GST collected on sales - GST credits on purchases. If negative, ATO owes you a refund.
Small business threshold: businesses with less than $75,000 turnover are not required to register for GST.`,

  abn: `ABN withholding:
If a contractor does not quote an ABN, you must withhold 47% (top marginal rate + 2% Medicare) from their payment.
Withholding amount must be sent to ATO via your BAS under W4 label.
Contractors with valid ABN: no withholding required (they handle their own tax).
ABN can be verified at abr.business.gov.au.
Sole traders are taxed as individuals on their net business income. No company tax rate.`,

  whm: `Working Holiday Makers (WHM) — visa 417 and 462:
Tax scale: 15% on first $45,000, 30% on $45,001-$135,000, 37% on $135,001-$190,000, 45% above $190,000.
No Medicare levy. No tax-free threshold. No LITO.
Super: WHMs are entitled to super at the SG rate (12%). They can claim it on departure via DASP (Departing Australia Superannuation Payment), taxed at 65%.
Employer must register as a Working Holiday Maker employer with ATO before hiring a WHM.`,

  payday_super: `Payday Super — mandatory from 1 July 2026:
Super must be paid on the same day or very close to every payday (not quarterly).
ATO will match payday super payments against payroll data reported through Single Touch Payroll (STP).
Penalties apply immediately from July 28, 2026 (first full payday after 1 July).
Super Guarantee Charge (SGC) is non-deductible and includes interest (10% p.a.) plus admin levy ($20 per employee per quarter).
Employers must use a clearing house or pay directly to the employee's chosen fund — no more holding super for 3 months.
Small Business Super Clearing House (SBSHC) is free for businesses with fewer than 19 employees or turnover under $10M.`,
}

// ── Helper: generate sequential invoice number ─────────────────────
async function nextInvoiceNumber(userId: string, supabase: SupabaseClient): Promise<string> {
  const { data } = await supabase
    .from('invoices')
    .select('invoice_number')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  if (data?.invoice_number) {
    const match = (data.invoice_number as string).match(/(\d+)$/)
    if (match) return `INV-${String(parseInt(match[1]) + 1).padStart(4, '0')}`
  }
  return 'INV-0001'
}

// ── Helper: generate sequential payslip number ──────────────────────
async function nextPayslipNumber(userId: string, supabase: SupabaseClient): Promise<string> {
  const { data } = await supabase
    .from('payslips')
    .select('payslip_number')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  if (data?.payslip_number) {
    const match = (data.payslip_number as string).match(/(\d+)$/)
    if (match) return `PAY-${String(parseInt(match[1]) + 1).padStart(4, '0')}`
  }
  return 'PAY-0001'
}

function fmt(n: number) {
  return `$${n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`
}

// ── Main dispatcher ────────────────────────────────────────────────
export async function executeToolCall(
  name: string,
  input: Record<string, unknown>,
  userId: string,
  supabase: SupabaseClient,
): Promise<Record<string, unknown>> {

  try {
    switch (name) {

      // ── create_client ───────────────────────────────────────────
      case 'create_client': {
        const { data: existing } = await supabase
          .from('clients')
          .select('id, business_name')
          .eq('user_id', userId)
          .ilike('business_name', (input.business_name as string).trim())
          .limit(1)
          .single()

        if (existing) {
          return { already_exists: true, client_id: existing.id, business_name: existing.business_name, message: 'Client already exists — use this ID for the invoice.' }
        }

        const { data: client, error } = await supabase.from('clients').insert({
          user_id:      userId,
          business_name: input.business_name as string,
          contact_name:  (input.contact_name as string) || null,
          email:         (input.email as string) || null,
          phone:         (input.phone as string) || null,
          abn:           (input.abn as string) || null,
          address:       (input.address as string) || null,
        }).select('id').single()

        if (error) throw new Error(error.message)

        return { ok: true, client_id: client.id, business_name: input.business_name, message: 'Client created. Now create the invoice.' }
      }

      // ── create_invoice ──────────────────────────────────────────
      case 'create_invoice': {
        const items = input.items as Array<{ label: string; amount: number }>
        const includeGst = input.include_gst as boolean
        const subtotal = items.reduce((s, i) => s + i.amount, 0)
        const gst = includeGst ? Math.round(subtotal * 0.1 * 100) / 100 : 0
        const total = subtotal + gst

        const today = new Date()
        const dueDate = new Date(today)
        dueDate.setDate(dueDate.getDate() + 14)

        const invoiceNumber = await nextInvoiceNumber(userId, supabase)

        const { data: biz } = await supabase
          .from('business_profiles')
          .select('business_name, abn, email, phone, address')
          .eq('id', userId)
          .single()

        const lineItems = items.map(i => ({
          description: i.label,
          qty: 1,
          unit_price: i.amount,
          total: i.amount,
        }))

        const { data: inv, error } = await supabase.from('invoices').insert({
          user_id:         userId,
          invoice_number:  invoiceNumber,
          status:          'draft',
          client_name:     (input.client_name as string) || '',
          client_email:    (input.client_email as string) || null,
          business_name:   (biz?.business_name as string) || '',
          business_abn:    (biz?.abn as string) || null,
          business_email:  (biz?.email as string) || null,
          line_items:      lineItems,
          has_gst:         includeGst,
          subtotal_ex_gst: subtotal,
          total_gst:       gst,
          total_inc_gst:   total,
          issue_date:      today.toISOString().slice(0, 10),
          due_date:        dueDate.toISOString().slice(0, 10),
          notes:           (input.description as string) || null,
        }).select('id').single()

        if (error) throw new Error(error.message)

        return {
          invoice_id:     inv.id,
          invoice_number: invoiceNumber,
          client_name:    input.client_name,
          client_email:   input.client_email,
          subtotal:       fmt(subtotal),
          gst:            fmt(gst),
          total:          fmt(total),
          due_date:       dueDate.toISOString().slice(0, 10),
          status:         'draft',
          rows: [
            ...items.map(i => [i.label, fmt(i.amount)]),
            includeGst ? ['GST (10%)', fmt(gst)] : null,
            ['Total', fmt(total)],
          ].filter(Boolean),
        }
      }

      // ── send_invoice ────────────────────────────────────────────
      case 'send_invoice': {
        const invoiceId  = input.invoice_id as string
        const clientEmail = input.client_email as string

        const { data: inv, error: fetchErr } = await supabase
          .from('invoices')
          .select('*')
          .eq('id', invoiceId)
          .eq('user_id', userId)
          .single()

        if (fetchErr || !inv) return { error: 'Invoice not found or access denied' }

        // Fetch business profile for logo, address, banking (fallback for fields not stored on invoice)
        const { data: bizPro } = await supabase
          .from('business_profiles')
          .select('address, logo_url, bank_name, account_name, bsb, account_number')
          .eq('id', userId)
          .single()

        const lineItems = (inv.line_items as Array<{ description: string; qty?: number; unit_price?: number; total?: number; amount?: number; has_gst?: boolean }>)
          .map(li => ({
            description: li.description,
            qty:         li.qty        ?? 1,
            unit_price:  li.unit_price ?? 0,
            amount:      li.amount     ?? li.total ?? 0,
            has_gst:     li.has_gst    ?? (inv.has_gst as boolean),
          }))

        const totalDue    = fmt(inv.total_inc_gst as number)
        const pdfBase64   = await getInvoicePDFBase64({
          invoice_number:       inv.invoice_number       as string,
          issue_date:           inv.issue_date           as string,
          due_date:             inv.due_date             as string,
          payment_terms:        (inv.payment_terms        as string | null) ?? 'Due on receipt',
          business_name:        (inv.business_name        as string) || '',
          business_abn:         (inv.business_abn         as string | null) ?? '',
          business_email:       (inv.business_email       as string | null) ?? '',
          business_phone:       (inv.business_phone       as string | null) ?? '',
          business_address:     (inv.business_address     as string | null) || (bizPro?.address      as string | null) || '',
          logo_url:             (bizPro?.logo_url         as string | null) ?? undefined,
          client_name:          inv.client_name           as string,
          client_business_name: (inv.client_business_name as string | null) ?? undefined,
          client_abn:           (inv.client_abn           as string | null) ?? '',
          client_email:         (inv.client_email         as string | null) ?? '',
          client_address:       (inv.client_address       as string | null) ?? '',
          line_items:           lineItems,
          subtotal_ex_gst:      inv.subtotal_ex_gst       as number,
          total_gst:            inv.total_gst             as number,
          total_inc_gst:        inv.total_inc_gst         as number,
          bank_name:            (inv.bank_name            as string | null) || (bizPro?.bank_name     as string | null) || '',
          account_name:         (inv.account_name         as string | null) || (bizPro?.account_name  as string | null) || '',
          bsb:                  (inv.bsb                  as string | null) || (bizPro?.bsb           as string | null) || '',
          account_number:       (inv.account_number       as string | null) || (bizPro?.account_number as string | null) || '',
          notes:                (inv.notes                as string | null) ?? '',
          document_type:        (inv.document_type        as 'invoice' | 'quote' | null) ?? 'invoice',
        })

        const pdfFilename  = `Invoice-${inv.invoice_number as string}-${(inv.business_name as string).replace(/\s+/g, '-')}.pdf`
        const clientAbn    = (inv.client_abn    as string | null) ?? ''
        const totalIncGst  = inv.total_inc_gst  as number
        const invLogoUrl   = bizPro?.logo_url && (bizPro.logo_url as string).startsWith('https://') ? (bizPro.logo_url as string) : ''
        const resend       = new Resend(process.env.RESEND_API_KEY)

        const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:#1C1917;padding:28px 36px">${invLogoUrl ? `<img src="${invLogoUrl}" alt="${(inv.business_name as string).replace(/"/g, '&quot;')}" style="max-height:60px;max-width:200px;object-fit:contain;margin-bottom:8px;display:block;" />` : ''}<p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${inv.business_name as string}</p><p style="margin:6px 0 0;color:#A09590;font-size:13px">Tax Invoice</p></td></tr><tr><td style="padding:36px"><p style="margin:0 0 8px;color:#1C1917;font-size:15px">Hi ${inv.client_name as string},</p><p style="margin:0 0 28px;color:#57534E;font-size:14px;line-height:1.6">Please find your invoice <strong>${inv.invoice_number as string}</strong> from <strong>${inv.business_name as string}</strong> attached to this email.</p><table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px"><tr><td style="padding:20px 24px"><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:6px 0;color:#78716C;font-size:13px">Invoice Number</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${inv.invoice_number as string}</td></tr><tr><td style="padding:6px 0;color:#78716C;font-size:13px">Due Date</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${inv.due_date as string}</td></tr>${clientAbn ? `<tr><td style="padding:6px 0;color:#78716C;font-size:13px">Your ABN</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${clientAbn}</td></tr>` : ''}<tr><td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Total Due (inc GST)</td><td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${totalDue}</td></tr></table></td></tr></table>${!clientAbn && totalIncGst >= 1000 ? `<p style="margin:0 0 16px;color:#92400E;font-size:12px;line-height:1.5;background:#FEF3C7;border-radius:6px;padding:10px 14px">Please provide your ABN to ${inv.business_name as string} for invoices over $1,000 (ATO requirement).</p>` : ''}<p style="margin:0 0 6px;color:#57534E;font-size:13px;line-height:1.6">Please reference the invoice number when making payment. If you have any questions, reply to this email or contact ${inv.business_name as string} directly.</p></td></tr><tr><td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5"><p style="margin:0;color:#A09590;font-size:11px;text-align:center">Generated by SAB Account AI</p></td></tr></table></td></tr></table></body></html>`

        const { error: sendErr } = await resend.emails.send({
          from:    process.env.EMAIL_FROM || 'onboarding@resend.dev',
          to:      [clientEmail],
          subject: `Invoice ${inv.invoice_number as string} from ${inv.business_name as string} — ${totalDue} due ${inv.due_date as string}`,
          html,
          attachments: [{ filename: pdfFilename, content: pdfBase64, contentType: 'application/pdf' }],
        })

        if (sendErr) throw new Error((sendErr as { message?: string }).message ?? 'Email send failed')

        await supabase.from('invoices').update({ status: 'pending' }).eq('id', invoiceId)

        return { ok: true, invoice_number: inv.invoice_number, sent_to: clientEmail, total: totalDue, pdf_attached: pdfFilename }
      }

      // ── create_payslip ──────────────────────────────────────────
      case 'create_payslip': {
        const employeeId = input.employee_id as string

        const { data: emp, error: empErr } = await supabase
          .from('employees')
          .select('*')
          .eq('id', employeeId)
          .eq('user_id', userId)
          .single()

        if (empErr || !emp) return { error: 'Employee not found or access denied' }

        // Auto-compute gross pay from stored employee data if not provided
        const payCycleStr = (emp.pay_cycle as string | null) || 'fortnightly'
        const payBasis    = (emp.pay_basis as string | null) || 'salary'
        let grossPay      = input.gross_pay as number | undefined

        type PayItemInput = { description: string; hours: number; rate_mult: number }
        const payItemInputs = (input.pay_items as PayItemInput[] | undefined) ?? []
        const ordinaryHoursOverride = input.ordinary_hours as number | undefined

        if (!grossPay) {
          if (payBasis === 'hourly') {
            const rate         = emp.hourly_rate as number | null
            const storedHours  = emp.ordinary_hours as number | null
            const ordHours     = ordinaryHoursOverride ?? storedHours
            if (!rate || !ordHours) return { error: `Cannot auto-compute pay: ${emp.name as string} has no hourly rate or ordinary hours on file. Please provide gross_pay or update the employee record.` }
            const ordinaryPay  = Math.round(rate * ordHours * 100) / 100
            const penaltyPay   = payItemInputs.reduce((s, i) => s + Math.round(rate * i.rate_mult * i.hours * 100) / 100, 0)
            grossPay = Math.round((ordinaryPay + penaltyPay) * 100) / 100
          } else {
            const annual = emp.annual_salary as number | null
            if (!annual) return { error: `Cannot auto-compute pay: ${emp.name as string} has no annual salary on file. Please provide gross_pay or update the employee record.` }
            const divisor = payCycleStr === 'weekly' ? 52 : payCycleStr === 'monthly' ? 12 : 26
            const basePay = Math.round((annual / divisor) * 100) / 100
            // For salaried employees, pay_items are loadings on top (passed as dollar amounts via rate_mult × base day rate)
            const penaltyPay = payItemInputs.reduce((s, i) => {
              const dayRate = annual / (52 * 5)
              return s + Math.round(dayRate * i.rate_mult * i.hours * 100) / 100
            }, 0)
            grossPay = Math.round((basePay + penaltyPay) * 100) / 100
          }
        }

        // Auto-compute pay period if not provided
        const todayDate = new Date()
        const todayStr  = todayDate.toISOString().slice(0, 10)
        let periodEnd   = (input.pay_period_end as string) || todayStr
        let periodStart = input.pay_period_start as string | undefined
        if (!periodStart) {
          const endDate = new Date(periodEnd)
          if (payCycleStr === 'weekly') {
            endDate.setDate(endDate.getDate() - 6)
          } else if (payCycleStr === 'monthly') {
            periodStart = new Date(endDate.getFullYear(), endDate.getMonth(), 1).toISOString().slice(0, 10)
            periodEnd   = new Date(endDate.getFullYear(), endDate.getMonth() + 1, 0).toISOString().slice(0, 10)
          } else {
            endDate.setDate(endDate.getDate() - 13)
          }
          if (!periodStart) periodStart = endDate.toISOString().slice(0, 10)
        }

        const { data: biz } = await supabase
          .from('business_profiles')
          .select('business_name, abn')
          .eq('id', userId)
          .single()

        const payCycle = payCycleStr === 'weekly' ? 'weekly' : payCycleStr === 'monthly' ? 'monthly' : 'fortnightly'

        const periodsPerYear = payCycle === 'weekly' ? 52 : payCycle === 'monthly' ? 12 : 26
        // For hourly employees, always derive annual from actual gross (includes penalty items)
        // For salary employees, use stored annual_salary for correct tax bands
        const annualSalary = payBasis === 'hourly'
          ? Math.round(grossPay! * periodsPerYear * 100) / 100
          : ((emp.annual_salary as number | null) ?? Math.round(grossPay! * periodsPerYear * 100) / 100)
        const residencyStatus = (emp.residency_status as 'citizen_pr' | 'student' | 'temp_work' | 'whm' | 'partner' | 'other_temp') ?? 'citizen_pr'

        const numbers = calculatePayslip({
          annualSalary,
          salarySacrifice:       (emp.salary_sacrifice as number | null) ?? 0,
          overtimeHours:         0,
          overtimeRate:          0,
          payCycle,
          claimingThreshold:     (emp.claiming_threshold as boolean | null) ?? true,
          hasHELP:               (emp.has_help           as boolean | null) ?? false,
          medicareLevyExemption: isMedicareExemptByResidency(residencyStatus),
          paymentDate:           new Date(periodEnd),
          residencyStatus,
        })

        const payslipNumber = await nextPayslipNumber(userId, supabase)
        const paymentDate   = periodEnd
        const baseRate      = (emp.hourly_rate as number | null) ?? 0
        const savedPayItems = payItemInputs.map(i => ({
          description: i.description,
          hours:       i.hours,
          rate:        Math.round(baseRate * i.rate_mult * 100) / 100,
        }))

        const { data: ps, error: psErr } = await supabase.from('payslips').insert({
          user_id:              userId,
          payslip_number:       payslipNumber,
          employee_name:        emp.name as string,
          employment_type:      (emp.employment_type as string) || 'casual',
          pay_cycle:            payCycle,
          super_fund_name:      (emp.super_fund_name as string | null) ?? null,
          member_number:        (emp.member_number as string | null) ?? null,
          employer_name:        (biz?.business_name as string) || '',
          employer_abn:         (biz?.abn as string | null) ?? null,
          pay_period_start:     periodStart!,
          pay_period_end:       periodEnd,
          payment_date:         paymentDate,
          gross_pay:            numbers.grossPay,
          salary_sacrifice:     numbers.salarySacrifice,
          taxable_gross:        numbers.taxableGross,
          income_tax:           numbers.incomeTax,
          medicare_levy:        numbers.medicareLevy,
          help_repayment:       numbers.helpRepayment,
          net_pay:              numbers.netPay,
          super_sg:             numbers.superSG,
          super_sal_sac:        numbers.superSalSac,
          pay_items:            savedPayItems,
          allowances:           [],
          leave_loading_amount: 0,
        }).select('id').single()

        if (psErr) throw new Error(psErr.message)

        const payItemLines = payItemInputs.map(i => ({
          description: i.description,
          hours:       i.hours,
          rate:        Math.round(baseRate * i.rate_mult * 100) / 100,
          total:       fmt(Math.round(baseRate * i.rate_mult * i.hours * 100) / 100),
        }))

        return {
          payslip_id:      ps.id,
          payslip_number:  payslipNumber,
          employee_name:   emp.name,
          employee_email:  emp.email,
          pay_period:      `${periodStart!} to ${periodEnd}`,
          gross_pay:       fmt(numbers.grossPay),
          income_tax:      fmt(numbers.incomeTax),
          medicare_levy:   fmt(numbers.medicareLevy),
          help_repayment:  fmt(numbers.helpRepayment),
          net_pay:         fmt(numbers.netPay),
          super_sg:        fmt(numbers.superSG),
          ...(payItemLines.length > 0 && { pay_items_applied: payItemLines }),
          rows: [
            ['Gross Pay',      fmt(numbers.grossPay)],
            ['Income Tax',     fmt(numbers.incomeTax)],
            ['Medicare Levy',  fmt(numbers.medicareLevy)],
            ...(numbers.helpRepayment > 0 ? [['HELP Repayment', fmt(numbers.helpRepayment)]] : []),
            ['Net Pay',        fmt(numbers.netPay)],
            ['Super (12%)',    fmt(numbers.superSG)],
          ],
        }
      }

      // ── send_payslip ────────────────────────────────────────────
      case 'send_payslip': {
        const payslipId    = input.payslip_id as string
        const employeeEmail = input.employee_email as string

        const { data: ps, error: fetchErr } = await supabase
          .from('payslips')
          .select('*')
          .eq('id', payslipId)
          .eq('user_id', userId)
          .single()

        if (fetchErr || !ps) return { error: 'Payslip not found or access denied' }

        // Fetch employee + business data for full-fidelity jsPDF
        const [{ data: emp }, { data: biz }] = await Promise.all([
          supabase.from('employees').select('pay_basis, annual_salary, hourly_rate, ordinary_hours, salary_sacrifice, claiming_threshold, has_help, residency_status, annual_leave_hours, personal_leave_hours, tfn').eq('user_id', userId).eq('name', ps.employee_name as string).maybeSingle(),
          supabase.from('business_profiles').select('address, logo_url').eq('id', userId).single(),
        ])

        // YTD: all payslips for this employee in the current ATO financial year up to (and including) this payslip
        const payDate     = new Date(ps.payment_date as string)
        const fyStartYear = payDate.getMonth() >= 6 ? payDate.getFullYear() : payDate.getFullYear() - 1
        const { data: ytdSlips } = await supabase
          .from('payslips')
          .select('gross_pay, income_tax, medicare_levy, help_repayment, super_sg, super_sal_sac')
          .eq('user_id', userId)
          .eq('employee_name', ps.employee_name as string)
          .gte('payment_date', `${fyStartYear}-07-01`)
          .lte('payment_date', ps.payment_date as string)
        const ytdGross = (ytdSlips ?? []).reduce((s, p) => s + (p.gross_pay      as number), 0)
        const ytdTax   = (ytdSlips ?? []).reduce((s, p) => s + (p.income_tax     as number) + (p.medicare_levy as number) + (p.help_repayment as number), 0)
        const ytdSuper = (ytdSlips ?? []).reduce((s, p) => s + (p.super_sg       as number) + (p.super_sal_sac as number), 0)

        const residencyStatus = (emp?.residency_status as string | null) ?? 'citizen_pr'

        const pdfBase64 = await getPayslipPDFBase64({
          payslip_number:    ps.payslip_number  as string,
          pay_period_start:  ps.pay_period_start as string,
          pay_period_end:    ps.pay_period_end  as string,
          payment_date:      ps.payment_date    as string,
          employer_name:     ps.employer_name   as string,
          employer_abn:      ps.employer_abn ? formatABN(ps.employer_abn as string) : '',
          employer_address:  (biz?.address      as string | null) ?? undefined,
          employee_name:     ps.employee_name   as string,
          employee_tfn:      (emp?.tfn          as string | null) ?? undefined,
          employment_type:   (ps.employment_type as string) || 'casual',
          pay_cycle:         (ps.pay_cycle      as string)  || 'fortnightly',
          pay_basis:         ((emp?.pay_basis   as string | null) === 'hourly' ? 'hourly' : 'salary'),
          annual_salary:     (emp?.annual_salary as number | null) ?? 0,
          hourly_rate:       (emp?.hourly_rate  as number | null) ?? 0,
          ordinary_hours:    (emp?.ordinary_hours as number | null) ?? 0,
          super_fund_name:   (ps.super_fund_name as string | null) ?? '',
          member_number:     (ps.member_number  as string | null) ?? '',
          claiming_threshold: (emp?.claiming_threshold as boolean | null) ?? true,
          has_help:           (emp?.has_help          as boolean | null) ?? false,
          medicare_exempt:    isMedicareExemptByResidency(residencyStatus as 'citizen_pr' | 'student' | 'temp_work' | 'whm' | 'partner' | 'other_temp'),
          residency_status:   residencyStatus,
          annual_leave_hours:   (emp?.annual_leave_hours   as number | null) ?? undefined,
          personal_leave_hours: (emp?.personal_leave_hours as number | null) ?? undefined,
          payItems:             (ps.pay_items as Array<{description: string; hours: number; rate: number}> | null) ?? [],
          allowances:           (ps.allowances as Array<{description: string; amount: number}> | null) ?? [],
          leave_loading_amount: (ps.leave_loading_amount as number | null) ?? 0,
          ytdIsActual: true,
          numbers: {
            ordinaryEarnings: ps.gross_pay       as number,
            overtimePay:      0,
            grossPay:         ps.gross_pay       as number,
            salarySacrifice:  ps.salary_sacrifice as number,
            taxableGross:     ps.taxable_gross   as number,
            incomeTax:        ps.income_tax      as number,
            medicareLevy:     ps.medicare_levy   as number,
            helpRepayment:    ps.help_repayment  as number,
            totalDeductions:  (ps.income_tax as number) + (ps.medicare_levy as number) + (ps.help_repayment as number),
            netPay:           ps.net_pay         as number,
            superSG:          ps.super_sg        as number,
            superSalSac:      ps.super_sal_sac   as number,
            totalSuper:       (ps.super_sg as number) + (ps.super_sal_sac as number),
            ytdGross,
            ytdTax,
            ytdSuper,
          },
        })

        const pdfFilename = `Payslip-${ps.payslip_number as string}-${(ps.employee_name as string).replace(/\s+/g, '-')}.pdf`
        const payPeriod   = `${ps.pay_period_start as string} to ${ps.pay_period_end as string}`
        const psLogoUrl   = biz?.logo_url && (biz.logo_url as string).startsWith('https://') ? (biz.logo_url as string) : ''

        const resend = new Resend(process.env.RESEND_API_KEY)
        const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:#1C1917;padding:28px 36px">${psLogoUrl ? `<img src="${psLogoUrl}" alt="${(ps.employer_name as string).replace(/"/g, '&quot;')}" style="max-height:60px;max-width:200px;object-fit:contain;margin-bottom:8px;display:block;" />` : ''}<p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${ps.employer_name as string}</p><p style="margin:6px 0 0;color:#A09590;font-size:13px">Payslip Notification</p></td></tr><tr><td style="padding:36px"><p style="margin:0 0 8px;color:#1C1917;font-size:15px">Hi ${ps.employee_name as string},</p><p style="margin:0 0 28px;color:#57534E;font-size:14px;line-height:1.6">Your payslip for <strong>${payPeriod}</strong> is ready. Please find it attached to this email.</p><table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px"><tr><td style="padding:20px 24px"><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:6px 0;color:#78716C;font-size:13px">Payslip Number</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${ps.payslip_number as string}</td></tr><tr><td style="padding:6px 0;color:#78716C;font-size:13px">Pay Period</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${payPeriod}</td></tr><tr><td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Net Pay</td><td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${fmt(ps.net_pay as number)}</td></tr></table></td></tr></table><p style="margin:0 0 6px;color:#57534E;font-size:13px;line-height:1.6">If you have any questions about your payslip, please contact your employer directly.</p></td></tr><tr><td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5"><p style="margin:0;color:#A09590;font-size:11px;text-align:center">Generated by SAB Account AI · ATO-compliant PAYG withholding</p></td></tr></table></td></tr></table></body></html>`

        const { error: sendErr } = await resend.emails.send({
          from:    process.env.EMAIL_FROM || 'onboarding@resend.dev',
          to:      [employeeEmail],
          subject: `Your payslip ${ps.payslip_number as string} from ${ps.employer_name as string}`,
          html,
          attachments: [{ filename: pdfFilename, content: pdfBase64, contentType: 'application/pdf' }],
        })

        if (sendErr) throw new Error((sendErr as { message?: string }).message ?? 'Email send failed')

        return { ok: true, payslip_number: ps.payslip_number, sent_to: employeeEmail, net_pay: fmt(ps.net_pay as number), pdf_attached: pdfFilename }
      }

      // ── get_bas_position ────────────────────────────────────────
      case 'get_bas_position': {
        const fy      = input.financial_year as string
        const quarter = input.quarter as number
        const [startYear] = fy.split('-').map(Number)

        const quarterRanges: Record<number, [string, string]> = {
          1: [`${startYear}-07-01`,   `${startYear}-09-30`],
          2: [`${startYear}-10-01`,   `${startYear}-12-31`],
          3: [`${startYear + 1}-01-01`, `${startYear + 1}-03-31`],
          4: [`${startYear + 1}-04-01`, `${startYear + 1}-06-30`],
        }
        const [from, to] = quarterRanges[quarter]

        const [{ data: invoices }, { data: records }, { data: payslipsW2 }] = await Promise.all([
          supabase.from('invoices').select('total_gst, total_inc_gst').eq('user_id', userId).gte('issue_date', from).lte('issue_date', to),
          supabase.from('records').select('gst_amount, type').eq('user_id', userId).eq('type', 'expense').gte('date', from).lte('date', to),
          supabase.from('payslips').select('income_tax, medicare_levy, help_repayment').eq('user_id', userId).gte('payment_date', from).lte('payment_date', to),
        ])

        const gstCollected  = (invoices    ?? []).reduce((s, i) => s + (i.total_gst   as number), 0)
        const gstCredits    = (records     ?? []).reduce((s, r) => s + (r.gst_amount  as number), 0)
        const paygWithheld  = (payslipsW2  ?? []).reduce((s, p) => s + (p.income_tax  as number) + (p.medicare_levy as number) + (p.help_repayment as number), 0)
        const netGst        = gstCollected - gstCredits
        const totalPayable  = netGst + paygWithheld
        const quarterNames  = ['', 'Q1 (Jul–Sep)', 'Q2 (Oct–Dec)', 'Q3 (Jan–Mar)', 'Q4 (Apr–Jun)']

        return {
          period:          `${quarterNames[quarter]} ${fy}`,
          gst_collected:   fmt(gstCollected),
          gst_credits:     fmt(gstCredits),
          net_gst:         fmt(Math.abs(netGst)),
          payg_withheld:   fmt(paygWithheld),
          total_payable:   fmt(totalPayable),
          outcome:         netGst > 0
            ? `GST payable ${fmt(netGst)}${paygWithheld > 0 ? ` + PAYG W2 ${fmt(paygWithheld)} = total ${fmt(totalPayable)} owing to ATO` : ' owing to ATO'}`
            : netGst < 0 ? `GST refund due ${fmt(Math.abs(netGst))}${paygWithheld > 0 ? ` (PAYG W2 ${fmt(paygWithheld)} still owing — net ${fmt(totalPayable)})` : ''}` : paygWithheld > 0 ? `Net zero GST — PAYG W2 ${fmt(paygWithheld)} owing to ATO` : 'Net zero — nothing owing',
          invoice_count:   invoices?.length ?? 0,
        }
      }

      // ── get_super_due ───────────────────────────────────────────
      case 'get_super_due': {
        const from = input.pay_period_start as string
        const to   = input.pay_period_end as string

        const { data: payslips } = await supabase
          .from('payslips')
          .select('employee_name, gross_pay, super_sg')
          .eq('user_id', userId)
          .gte('pay_period_start', from)
          .lte('pay_period_end', to)

        const perEmployee: Record<string, { count: number; gross: number; super: number }> = {}
        for (const ps of payslips ?? []) {
          const key = ps.employee_name as string
          if (!perEmployee[key]) perEmployee[key] = { count: 0, gross: 0, super: 0 }
          perEmployee[key].count++
          perEmployee[key].gross  += ps.gross_pay as number
          perEmployee[key].super  += ps.super_sg as number
        }

        const breakdown = Object.entries(perEmployee).map(([name, d]) => ({
          employee: name,
          gross:    fmt(d.gross),
          super_due: fmt(d.super),
          payslips: d.count,
        }))

        const totalSuper = Object.values(perEmployee).reduce((s, d) => s + d.super, 0)

        return {
          period:      `${from} to ${to}`,
          total_super: fmt(totalSuper),
          sg_rate:     '12%',
          breakdown,
          payday_super_note: 'From 1 July 2026, super must be paid on every payday. Ensure your clearing house receives payment by each pay date.',
        }
      }

      // ── get_business_summary ────────────────────────────────────
      case 'get_business_summary': {
        const from = input.date_from as string
        const to   = input.date_to as string

        const [{ data: invoices }, { data: records }] = await Promise.all([
          supabase.from('invoices').select('total_inc_gst, total_gst').eq('user_id', userId).gte('issue_date', from).lte('issue_date', to),
          supabase.from('records').select('amount, gst_amount, type').eq('user_id', userId).gte('date', from).lte('date', to),
        ])

        const totalIncome   = (invoices ?? []).reduce((s, i) => s + (i.total_inc_gst as number), 0)
        const gstCollected  = (invoices ?? []).reduce((s, i) => s + (i.total_gst as number), 0)
        const totalExpenses = (records  ?? []).filter(r => (r.type as string) === 'expense').reduce((s, r) => s + (r.amount as number), 0)
        const gstCredits    = (records  ?? []).filter(r => (r.type as string) === 'expense').reduce((s, r) => s + (r.gst_amount as number), 0)
        const netProfit     = totalIncome - totalExpenses

        return {
          period:        `${from} to ${to}`,
          total_income:   fmt(totalIncome),
          gst_collected:  fmt(gstCollected),
          total_expenses: fmt(totalExpenses),
          gst_credits:    fmt(gstCredits),
          net_profit:     fmt(netProfit),
          invoice_count:  invoices?.length ?? 0,
          profitable:     netProfit >= 0,
        }
      }

      // ── get_ato_rules ───────────────────────────────────────────
      case 'get_ato_rules': {
        const topic = input.topic as string
        const rules = ATO_RULES[topic]
        if (!rules) return { error: `Unknown topic: ${topic}` }
        return { topic, rules }
      }

      // ── process_payroll ─────────────────────────────────────────
      case 'process_payroll': {
        const overrideStart = input.pay_period_start as string | undefined
        const overrideEnd   = input.pay_period_end   as string | undefined
        const filterIds     = (input.employee_ids as string[] | undefined) ?? []

        const { data: biz } = await supabase
          .from('business_profiles')
          .select('business_name, abn')
          .eq('id', userId)
          .single()

        let query = supabase.from('employees').select('*').eq('user_id', userId).order('name')
        if (filterIds.length > 0) query = query.in('id', filterIds)
        const { data: employees } = await query

        if (!employees || employees.length === 0) return { error: 'No employees found.' }

        const todayStr = new Date().toISOString().slice(0, 10)
        const results: Array<{
          employee_name: string
          employee_email: string | null
          payslip_id: string
          payslip_number: string
          gross_pay: number
          net_pay: number
          super_sg: number
          pay_period: string
          error?: string
        }> = []

        for (const emp of employees) {
          try {
            const payCycleStr = (emp.pay_cycle as string | null) || 'fortnightly'
            const payBasis    = (emp.pay_basis  as string | null) || 'salary'
            const payCycle    = payCycleStr === 'weekly' ? 'weekly' : payCycleStr === 'monthly' ? 'monthly' : 'fortnightly'

            // Compute gross pay
            let grossPay: number
            if (payBasis === 'hourly') {
              const rate  = emp.hourly_rate   as number | null
              const hours = emp.ordinary_hours as number | null
              if (!rate || !hours) { results.push({ employee_name: emp.name as string, employee_email: emp.email as string | null, payslip_id: '', payslip_number: '', gross_pay: 0, net_pay: 0, super_sg: 0, pay_period: '', error: 'No hourly rate/hours on file — skipped' }); continue }
              grossPay = Math.round(rate * hours * 100) / 100
            } else {
              const annual = emp.annual_salary as number | null
              if (!annual) { results.push({ employee_name: emp.name as string, employee_email: emp.email as string | null, payslip_id: '', payslip_number: '', gross_pay: 0, net_pay: 0, super_sg: 0, pay_period: '', error: 'No annual salary on file — skipped' }); continue }
              const divisor = payCycle === 'weekly' ? 52 : payCycle === 'monthly' ? 12 : 26
              grossPay = Math.round((annual / divisor) * 100) / 100
            }

            // Compute pay period
            let periodEnd   = overrideEnd   || todayStr
            let periodStart = overrideStart
            if (!periodStart) {
              const endDate = new Date(periodEnd)
              if (payCycle === 'weekly') {
                const s = new Date(endDate); s.setDate(s.getDate() - 6); periodStart = s.toISOString().slice(0, 10)
              } else if (payCycle === 'monthly') {
                periodStart = new Date(endDate.getFullYear(), endDate.getMonth(), 1).toISOString().slice(0, 10)
                periodEnd   = new Date(endDate.getFullYear(), endDate.getMonth() + 1, 0).toISOString().slice(0, 10)
              } else {
                const s = new Date(endDate); s.setDate(s.getDate() - 13); periodStart = s.toISOString().slice(0, 10)
              }
            }

            const annualSalary = (emp.annual_salary as number | null) ?? (grossPay * (payCycle === 'weekly' ? 52 : payCycle === 'monthly' ? 12 : 26))
            const residencyStatus = (emp.residency_status as 'citizen_pr' | 'student' | 'temp_work' | 'whm' | 'partner' | 'other_temp') ?? 'citizen_pr'
            const numbers = calculatePayslip({
              annualSalary,
              salarySacrifice:       (emp.salary_sacrifice as number | null) ?? 0,
              overtimeHours:         0,
              overtimeRate:          0,
              payCycle,
              claimingThreshold:     (emp.claiming_threshold as boolean | null) ?? true,
              hasHELP:               (emp.has_help           as boolean | null) ?? false,
              medicareLevyExemption: isMedicareExemptByResidency(residencyStatus),
              paymentDate:           new Date(periodEnd),
              residencyStatus,
            })

            const payslipNumber = await nextPayslipNumber(userId, supabase)

            const { data: ps, error: psErr } = await supabase.from('payslips').insert({
              user_id:          userId,
              payslip_number:   payslipNumber,
              employee_name:    emp.name as string,
              employment_type:  (emp.employment_type as string) || 'casual',
              pay_cycle:        payCycle,
              super_fund_name:  (emp.super_fund_name  as string | null) ?? null,
              member_number:    (emp.member_number    as string | null) ?? null,
              employer_name:    (biz?.business_name   as string) || '',
              employer_abn:     (biz?.abn             as string | null) ?? null,
              pay_period_start: periodStart,
              pay_period_end:   periodEnd,
              payment_date:     periodEnd,
              gross_pay:        numbers.grossPay,
              salary_sacrifice: numbers.salarySacrifice,
              taxable_gross:    numbers.taxableGross,
              income_tax:       numbers.incomeTax,
              medicare_levy:    numbers.medicareLevy,
              help_repayment:   numbers.helpRepayment,
              net_pay:          numbers.netPay,
              super_sg:         numbers.superSG,
              super_sal_sac:    numbers.superSalSac,
            }).select('id').single()

            if (psErr) throw new Error(psErr.message)

            results.push({
              employee_name:  emp.name as string,
              employee_email: (emp.email as string | null) ?? null,
              payslip_id:     ps.id,
              payslip_number: payslipNumber,
              gross_pay:      numbers.grossPay,
              net_pay:        numbers.netPay,
              super_sg:       numbers.superSG,
              pay_period:     `${periodStart} to ${periodEnd}`,
            })
          } catch (empErr) {
            results.push({ employee_name: emp.name as string, employee_email: emp.email as string | null, payslip_id: '', payslip_number: '', gross_pay: 0, net_pay: 0, super_sg: 0, pay_period: '', error: empErr instanceof Error ? empErr.message : 'Failed' })
          }
        }

        const successful = results.filter(r => !r.error)
        const failed     = results.filter(r => r.error)
        const totalNet   = successful.reduce((s, r) => s + r.net_pay, 0)
        const totalSuper = successful.reduce((s, r) => s + r.super_sg, 0)

        return {
          processed:   successful.length,
          failed:      failed.length,
          failed_list: failed.map(r => `${r.employee_name}: ${r.error}`),
          total_net:   fmt(totalNet),
          total_super: fmt(totalSuper),
          payslips:    successful.map(r => ({
            payslip_id:     r.payslip_id,
            payslip_number: r.payslip_number,
            employee_name:  r.employee_name,
            employee_email: r.employee_email,
            net_pay:        fmt(r.net_pay),
            gross_pay:      fmt(r.gross_pay),
            super_sg:       fmt(r.super_sg),
            pay_period:     r.pay_period,
          })),
          rows: [
            ...successful.map(r => [r.employee_name, `Net ${fmt(r.net_pay)} | Super ${fmt(r.super_sg)}`]),
            ['─────────────', '─────────────────────'],
            ['Total Net Pay', fmt(totalNet)],
            ['Total Super',   fmt(totalSuper)],
          ],
        }
      }

      // ── send_all_payslips ───────────────────────────────────────
      case 'send_all_payslips': {
        const payslips = input.payslips as Array<{ payslip_id: string; employee_email: string; employee_name?: string }>
        const resend   = new Resend(process.env.RESEND_API_KEY)

        const { data: biz } = await supabase
          .from('business_profiles')
          .select('business_name, address, logo_url')
          .eq('id', userId)
          .single()

        const sentResults: Array<{ name: string; email: string; ok: boolean; error?: string }> = []

        for (const item of payslips) {
          if (!item.employee_email) {
            sentResults.push({ name: item.employee_name || 'Unknown', email: '', ok: false, error: 'No email address on file' })
            continue
          }

          const { data: ps, error: fetchErr } = await supabase
            .from('payslips')
            .select('*')
            .eq('id', item.payslip_id)
            .eq('user_id', userId)
            .single()

          if (fetchErr || !ps) { sentResults.push({ name: item.employee_name || 'Unknown', email: item.employee_email, ok: false, error: 'Payslip not found' }); continue }

          // Fetch employee record and YTD for full-fidelity PDF
          const { data: emp } = await supabase.from('employees').select('pay_basis, annual_salary, hourly_rate, ordinary_hours, claiming_threshold, has_help, residency_status, annual_leave_hours, personal_leave_hours, tfn').eq('user_id', userId).eq('name', ps.employee_name as string).maybeSingle()
          const payDate     = new Date(ps.payment_date as string)
          const fyStartYear = payDate.getMonth() >= 6 ? payDate.getFullYear() : payDate.getFullYear() - 1
          const { data: ytdSlips } = await supabase.from('payslips').select('gross_pay, income_tax, medicare_levy, help_repayment, super_sg, super_sal_sac').eq('user_id', userId).eq('employee_name', ps.employee_name as string).gte('payment_date', `${fyStartYear}-07-01`).lte('payment_date', ps.payment_date as string)
          const ytdGross = (ytdSlips ?? []).reduce((s, p) => s + (p.gross_pay      as number), 0)
          const ytdTax   = (ytdSlips ?? []).reduce((s, p) => s + (p.income_tax     as number) + (p.medicare_levy as number) + (p.help_repayment as number), 0)
          const ytdSuper = (ytdSlips ?? []).reduce((s, p) => s + (p.super_sg       as number) + (p.super_sal_sac as number), 0)
          const residencyStatus = (emp?.residency_status as string | null) ?? 'citizen_pr'

          const pdfBase64 = await getPayslipPDFBase64({
            payslip_number:    ps.payslip_number  as string,
            pay_period_start:  ps.pay_period_start as string,
            pay_period_end:    ps.pay_period_end  as string,
            payment_date:      ps.payment_date    as string,
            employer_name:     ps.employer_name   as string,
            employer_abn:      ps.employer_abn ? formatABN(ps.employer_abn as string) : '',
            employer_address:  (biz?.address      as string | null) ?? undefined,
            employee_name:     ps.employee_name   as string,
            employee_tfn:      (emp?.tfn          as string | null) ?? undefined,
            employment_type:   (ps.employment_type as string) || 'casual',
            pay_cycle:         (ps.pay_cycle      as string)  || 'fortnightly',
            pay_basis:         ((emp?.pay_basis   as string | null) === 'hourly' ? 'hourly' : 'salary'),
            annual_salary:     (emp?.annual_salary as number | null) ?? 0,
            hourly_rate:       (emp?.hourly_rate  as number | null) ?? 0,
            ordinary_hours:    (emp?.ordinary_hours as number | null) ?? 0,
            super_fund_name:   (ps.super_fund_name as string | null) ?? '',
            member_number:     (ps.member_number  as string | null) ?? '',
            claiming_threshold: (emp?.claiming_threshold as boolean | null) ?? true,
            has_help:           (emp?.has_help          as boolean | null) ?? false,
            medicare_exempt:    isMedicareExemptByResidency(residencyStatus as 'citizen_pr' | 'student' | 'temp_work' | 'whm' | 'partner' | 'other_temp'),
            residency_status:   residencyStatus,
            annual_leave_hours:   (emp?.annual_leave_hours   as number | null) ?? undefined,
            personal_leave_hours: (emp?.personal_leave_hours as number | null) ?? undefined,
            payItems: [],
            allowances: [],
            leave_loading_amount: 0,
            ytdIsActual: true,
            numbers: {
              ordinaryEarnings: ps.gross_pay       as number,
              overtimePay:      0,
              grossPay:         ps.gross_pay       as number,
              salarySacrifice:  ps.salary_sacrifice as number,
              taxableGross:     ps.taxable_gross   as number,
              incomeTax:        ps.income_tax      as number,
              medicareLevy:     ps.medicare_levy   as number,
              helpRepayment:    ps.help_repayment  as number,
              totalDeductions:  (ps.income_tax as number) + (ps.medicare_levy as number) + (ps.help_repayment as number),
              netPay:           ps.net_pay         as number,
              superSG:          ps.super_sg        as number,
              superSalSac:      ps.super_sal_sac   as number,
              totalSuper:       (ps.super_sg as number) + (ps.super_sal_sac as number),
              ytdGross, ytdTax, ytdSuper,
            },
          })

          const pdfFilename = `Payslip-${ps.payslip_number as string}-${(ps.employee_name as string).replace(/\s+/g, '-')}.pdf`
          const payPeriod   = `${ps.pay_period_start as string} to ${ps.pay_period_end as string}`
          const allLogoUrl  = biz?.logo_url && (biz.logo_url as string).startsWith('https://') ? (biz.logo_url as string) : ''
          const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif"><table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0"><tr><td align="center"><table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)"><tr><td style="background:#1C1917;padding:28px 36px">${allLogoUrl ? `<img src="${allLogoUrl}" alt="${(ps.employer_name as string).replace(/"/g, '&quot;')}" style="max-height:60px;max-width:200px;object-fit:contain;margin-bottom:8px;display:block;" />` : ''}<p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${ps.employer_name as string}</p><p style="margin:6px 0 0;color:#A09590;font-size:13px">Payslip Notification</p></td></tr><tr><td style="padding:36px"><p style="margin:0 0 8px;color:#1C1917;font-size:15px">Hi ${ps.employee_name as string},</p><p style="margin:0 0 28px;color:#57534E;font-size:14px;line-height:1.6">Your payslip for <strong>${payPeriod}</strong> is ready. Please find it attached to this email.</p><table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px"><tr><td style="padding:20px 24px"><table width="100%" cellpadding="0" cellspacing="0"><tr><td style="padding:6px 0;color:#78716C;font-size:13px">Payslip Number</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${ps.payslip_number as string}</td></tr><tr><td style="padding:6px 0;color:#78716C;font-size:13px">Pay Period</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${payPeriod}</td></tr><tr><td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Net Pay</td><td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${fmt(ps.net_pay as number)}</td></tr></table></td></tr></table><p style="margin:0 0 6px;color:#57534E;font-size:13px;line-height:1.6">If you have any questions about your payslip, please contact your employer directly.</p></td></tr><tr><td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5"><p style="margin:0;color:#A09590;font-size:11px;text-align:center">Generated by SAB Account AI · ATO-compliant PAYG withholding</p></td></tr></table></td></tr></table></body></html>`

          const { error: sendErr } = await resend.emails.send({
            from:    process.env.EMAIL_FROM || 'onboarding@resend.dev',
            to:      [item.employee_email],
            subject: `Your payslip ${ps.payslip_number as string} from ${ps.employer_name as string}`,
            html,
            attachments: [{ filename: pdfFilename, content: pdfBase64, contentType: 'application/pdf' }],
          })

          sentResults.push({ name: ps.employee_name as string, email: item.employee_email, ok: !sendErr, error: sendErr ? (sendErr as { message?: string }).message : undefined })
        }

        const sent   = sentResults.filter(r => r.ok)
        const failed = sentResults.filter(r => !r.ok)

        return {
          sent:       sent.length,
          failed:     failed.length,
          sent_to:    sent.map(r => `${r.name} <${r.email}>`),
          failed_list: failed.map(r => `${r.name}: ${r.error}`),
          message:    `Sent ${sent.length} payslip${sent.length !== 1 ? 's' : ''}${failed.length > 0 ? `, ${failed.length} failed (no email on file)` : ''}`,
        }
      }

      // ── send_bas_to_accountant ──────────────────────────────────
      case 'send_bas_to_accountant': {
        const fy             = input.financial_year as string
        const quarter        = input.quarter as number
        const accountantEmail = input.accountant_email as string
        const accountantName  = (input.accountant_name as string) || 'Accountant'
        const [startYear]    = fy.split('-').map(Number)

        const quarterRanges: Record<number, [string, string]> = {
          1: [`${startYear}-07-01`,     `${startYear}-09-30`],
          2: [`${startYear}-10-01`,     `${startYear}-12-31`],
          3: [`${startYear + 1}-01-01`, `${startYear + 1}-03-31`],
          4: [`${startYear + 1}-04-01`, `${startYear + 1}-06-30`],
        }
        const [from, to] = quarterRanges[quarter]
        const quarterNames = ['', 'Q1 (Jul–Sep)', 'Q2 (Oct–Dec)', 'Q3 (Jan–Mar)', 'Q4 (Apr–Jun)']
        const periodLabel = `${quarterNames[quarter]} ${fy}`

        const [{ data: biz }, { data: invoices }, { data: records }, { data: payslipsW2 }] = await Promise.all([
          supabase.from('business_profiles').select('business_name, abn, email').eq('id', userId).single(),
          supabase.from('invoices').select('invoice_number, client_name, total_inc_gst, total_gst, issue_date').eq('user_id', userId).gte('issue_date', from).lte('issue_date', to).order('issue_date', { ascending: false }),
          supabase.from('records').select('amount, gst_amount, type, description, date').eq('user_id', userId).gte('date', from).lte('date', to),
          supabase.from('payslips').select('income_tax, medicare_levy, help_repayment').eq('user_id', userId).gte('payment_date', from).lte('payment_date', to),
        ])

        const gstCollected  = (invoices   ?? []).reduce((s, i) => s + (i.total_gst    as number), 0)
        const totalIncome   = (invoices   ?? []).reduce((s, i) => s + (i.total_inc_gst as number), 0)
        const expenses      = (records    ?? []).filter(r => (r.type as string) === 'expense')
        const gstCredits    = expenses.reduce((s, r) => s + (r.gst_amount as number), 0)
        const totalExpenses = expenses.reduce((s, r) => s + (r.amount     as number), 0)
        const paygWithheld  = (payslipsW2 ?? []).reduce((s, p) => s + (p.income_tax as number) + (p.medicare_levy as number) + (p.help_repayment as number), 0)
        const netGst        = gstCollected - gstCredits
        const totalPayable  = netGst + paygWithheld
        const outcome       = netGst > 0 ? `Net GST payable to ATO: ${fmt(netGst)}` : netGst < 0 ? `GST refund from ATO: ${fmt(Math.abs(netGst))}` : 'Net zero — nothing owing'

        const invoiceRows = (invoices ?? []).map(i =>
          `<tr><td style="padding:5px 0;color:#57534E;font-size:13px">${i.invoice_number as string}</td><td style="padding:5px 0;color:#57534E;font-size:13px">${i.client_name as string}</td><td style="padding:5px 0;color:#57534E;font-size:13px">${i.issue_date as string}</td><td align="right" style="padding:5px 0;color:#1C1917;font-size:13px;font-weight:600">${fmt(i.total_inc_gst as number)}</td><td align="right" style="padding:5px 0;color:#57534E;font-size:12px">${fmt(i.total_gst as number)}</td></tr>`
        ).join('')

        const html = `<!DOCTYPE html><html><body style="font-family:-apple-system,sans-serif;background:#F5F0E8;margin:0;padding:40px 0">
<table width="620" align="center" style="background:#fff;border-radius:10px;overflow:hidden">
<tr><td style="background:#1C1917;padding:28px 36px">
  <p style="margin:0;color:#fff;font-size:18px;font-weight:700">${(biz?.business_name as string) || 'Your Business'}</p>
  <p style="margin:6px 0 0;color:#A09590;font-size:13px">BAS Summary — ${periodLabel}</p>
  ${biz?.abn ? `<p style="margin:4px 0 0;color:#A09590;font-size:12px">ABN: ${biz.abn as string}</p>` : ''}
</td></tr>
<tr><td style="padding:36px">
  <p style="color:#1C1917;font-size:15px">Dear ${accountantName},</p>
  <p style="color:#57534E;font-size:14px">Please find the BAS summary for <strong>${periodLabel}</strong> below.</p>

  <table width="100%" style="background:#F5F0E8;border-radius:8px;margin:20px 0"><tr><td style="padding:20px 24px">
  <table width="100%">
    <tr><td style="padding:6px 0;color:#57534E;font-size:13px">Total Income (inc. GST)</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${fmt(totalIncome)}</td></tr>
    <tr><td style="padding:6px 0;color:#57534E;font-size:13px">GST Collected (1A)</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${fmt(gstCollected)}</td></tr>
    <tr><td style="padding:6px 0;color:#57534E;font-size:13px">Total Expenses (inc. GST)</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${fmt(totalExpenses)}</td></tr>
    <tr><td style="padding:6px 0;color:#57534E;font-size:13px">GST Credits (1B)</td><td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${fmt(gstCredits)}</td></tr>
    <tr><td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">${netGst >= 0 ? 'Net GST Payable' : 'GST Refund Due'}</td><td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${fmt(Math.abs(netGst))}</td></tr>
    ${paygWithheld > 0 ? `<tr><td style="padding:6px 0;color:#57534E;font-size:13px;border-top:1px solid #E5DDD5">PAYG Withholding — W2 (from payslips)</td><td align="right" style="padding:6px 0;color:#C84B2F;font-size:13px;font-weight:700">${fmt(paygWithheld)}</td></tr><tr><td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Total Payable to ATO</td><td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${fmt(totalPayable)}</td></tr>` : ''}
    <tr><td colspan="2" style="padding:6px 0;color:#57534E;font-size:12px;font-style:italic">${outcome}</td></tr>
  </table>
  </td></tr></table>

  ${(invoices ?? []).length > 0 ? `
  <p style="color:#1C1917;font-size:14px;font-weight:600;margin-top:24px">Invoices (${(invoices ?? []).length})</p>
  <table width="100%" style="border-collapse:collapse">
    <tr style="border-bottom:1px solid #E5DDD5"><th align="left" style="padding:6px 0;color:#A09590;font-size:11px;font-weight:600">NUMBER</th><th align="left" style="padding:6px 0;color:#A09590;font-size:11px;font-weight:600">CLIENT</th><th align="left" style="padding:6px 0;color:#A09590;font-size:11px;font-weight:600">DATE</th><th align="right" style="padding:6px 0;color:#A09590;font-size:11px;font-weight:600">TOTAL</th><th align="right" style="padding:6px 0;color:#A09590;font-size:11px;font-weight:600">GST</th></tr>
    ${invoiceRows}
  </table>` : ''}

  <p style="color:#A09590;font-size:11px;text-align:center;margin-top:32px">Generated by SAB Account AI · sabaccountai.com</p>
</td></tr></table></body></html>`

        // Generate PDF attachment
        const pdfBuffer = await generateBasPdf({
          businessName:  (biz?.business_name as string) || 'Your Business',
          abn:           (biz?.abn as string) || '',
          period:        periodLabel,
          totalIncome,
          gstCollected,
          totalExpenses,
          gstCredits,
          netGst,
          paygWithheld,
          invoices: (invoices ?? []).map(i => ({
            invoice_number: i.invoice_number as string,
            client_name:    i.client_name    as string,
            issue_date:     i.issue_date     as string,
            total_inc_gst:  i.total_inc_gst  as number,
            total_gst:      i.total_gst      as number,
          })),
          generatedDate: new Date().toLocaleDateString('en-AU'),
        })

        const resend = new Resend(process.env.RESEND_API_KEY)
        const filename = `BAS-${periodLabel.replace(/[^a-zA-Z0-9-]/g, '-')}-${((biz?.business_name as string) || 'Business').replace(/\s+/g, '-')}.pdf`

        const { error: sendErr } = await resend.emails.send({
          from:    process.env.EMAIL_FROM || 'onboarding@resend.dev',
          to:      [accountantEmail],
          subject: `BAS Summary ${periodLabel} — ${(biz?.business_name as string) || 'Your Business'}`,
          html,
          attachments: [{
            filename,
            content: pdfBuffer.toString('base64'),
            contentType: 'application/pdf',
          }],
        })

        if (sendErr) throw new Error((sendErr as { message?: string }).message ?? 'Email send failed')

        return {
          ok:               true,
          period:           periodLabel,
          sent_to:          accountantEmail,
          gst_collected:    fmt(gstCollected),
          gst_credits:      fmt(gstCredits),
          net_gst:          fmt(Math.abs(netGst)),
          payg_withheld:    fmt(paygWithheld),
          total_payable:    fmt(totalPayable),
          outcome,
          invoice_count:    invoices?.length ?? 0,
          pdf_attached:     filename,
        }
      }

      // ── default ─────────────────────────────────────────────────
      default:
        return { error: `Unknown tool: ${name}` }
    }
  } catch (err) {
    Sentry.captureException(err, { tags: { feature: 'sab_chat', tool: name } })
    return { error: err instanceof Error ? err.message : `Tool ${name} failed` }
  }
}
