import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import * as Sentry from '@sentry/nextjs'
import { createServiceClient } from '@/lib/supabase'
import { escHtml as esc, escSubject } from '@/lib/email-utils'

export async function POST(req: NextRequest) {
  const resend = new Resend(process.env.RESEND_API_KEY)
  const token = req.headers.get('Authorization')?.replace('Bearer ', '')
  if (!token) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const supabase = createServiceClient()
  const { data: { user }, error: authErr } = await supabase.auth.getUser(token)
  if (authErr || !user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  const {
    to, paymentType, recipientName, businessName,
    workDescription, paymentDate, grossAmount, netPayable, withholdingAmount,
    pdfBase64,
  } = await req.json() as {
    to: string
    paymentType: 'abn' | 'noabn'
    recipientName: string
    businessName: string
    workDescription: string
    paymentDate: string
    grossAmount: string
    netPayable: string
    withholdingAmount?: string
    pdfBase64: string
  }

  if (!to || !pdfBase64) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }
  if (pdfBase64.length > 5_000_000) {
    return NextResponse.json({ error: 'PDF too large' }, { status: 400 })
  }

  const isABN = paymentType === 'abn'

  const html = isABN ? `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)">
        <tr>
          <td style="background:#1C1917;padding:28px 36px">
            <p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${esc(businessName) || 'Your Client'}</p>
            <p style="margin:6px 0 0;color:#A09590;font-size:13px">Remittance Statement</p>
          </td>
        </tr>
        <tr>
          <td style="padding:36px">
            <p style="margin:0 0 8px;color:#1C1917;font-size:15px">Hi ${esc(recipientName)},</p>
            <p style="margin:0 0 28px;color:#57534E;font-size:14px;line-height:1.6">
              Please find your Remittance Statement from <strong>${esc(businessName)}</strong> attached. This document confirms payment for the services outlined below.
            </p>
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px">
              <tr>
                <td style="padding:20px 24px">
                  <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                      <td style="padding:6px 0;color:#78716C;font-size:13px">Services</td>
                      <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(workDescription)}</td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;color:#78716C;font-size:13px">Payment Date</td>
                      <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(paymentDate)}</td>
                    </tr>
                    <tr>
                      <td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Total Payment</td>
                      <td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${esc(grossAmount)}</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <p style="margin:0;color:#57534E;font-size:13px;line-height:1.6">
              Please keep this statement for your tax records. If you have any questions, contact ${esc(businessName)} directly.
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5">
            <p style="margin:0;color:#A09590;font-size:11px;text-align:center">Generated by SAB Account AI · ABN Contractor Payment</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>` : `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F5F0E8;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;padding:40px 0">
    <tr><td align="center">
      <table width="560" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:10px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08)">
        <tr>
          <td style="background:#C84B2F;padding:28px 36px">
            <p style="margin:0;color:#ffffff;font-size:18px;font-weight:700;letter-spacing:-0.3px">${esc(businessName) || 'Your Payer'}</p>
            <p style="margin:6px 0 0;color:rgba(255,255,255,0.7);font-size:13px">No-ABN Withholding Statement</p>
          </td>
        </tr>
        <tr>
          <td style="padding:36px">
            <p style="margin:0 0 8px;color:#1C1917;font-size:15px">Hi ${esc(recipientName)},</p>
            <p style="margin:0 0 28px;color:#57534E;font-size:14px;line-height:1.6">
              Please find your Withholding Statement from <strong>${esc(businessName)}</strong> attached. As no ABN was quoted, tax withholding was applied under ATO requirements.
            </p>
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#F5F0E8;border-radius:8px;margin-bottom:28px">
              <tr>
                <td style="padding:20px 24px">
                  <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                      <td style="padding:6px 0;color:#78716C;font-size:13px">Services</td>
                      <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(workDescription)}</td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;color:#78716C;font-size:13px">Payment Date</td>
                      <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(paymentDate)}</td>
                    </tr>
                    <tr>
                      <td style="padding:6px 0;color:#78716C;font-size:13px">Gross Amount</td>
                      <td align="right" style="padding:6px 0;color:#1C1917;font-size:13px;font-weight:600">${esc(grossAmount)}</td>
                    </tr>
                    ${withholdingAmount ? `
                    <tr>
                      <td style="padding:6px 0;color:#78716C;font-size:13px">W4 Withheld (47%)</td>
                      <td align="right" style="padding:6px 0;color:#C84B2F;font-size:13px;font-weight:600">(${esc(withholdingAmount)})</td>
                    </tr>` : ''}
                    <tr>
                      <td style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#1C1917;font-size:14px;font-weight:700">Net Paid to You</td>
                      <td align="right" style="padding:10px 0 6px;border-top:1px solid #E5DDD5;color:#C84B2F;font-size:18px;font-weight:700">${esc(netPayable)}</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <p style="margin:0;color:#57534E;font-size:13px;line-height:1.6">
              Please keep this statement for your tax records. The withheld amount has been remitted to the ATO on your behalf.
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#F5F0E8;padding:20px 36px;border-top:1px solid #E5DDD5">
            <p style="margin:0;color:#A09590;font-size:11px;text-align:center">Generated by SAB Account AI · ATO No-ABN Withholding</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`

  const subject = isABN
    ? `Remittance Statement from ${escSubject(businessName)} — ${grossAmount}`
    : `Withholding Statement from ${escSubject(businessName)} — ${paymentDate}`

  const filename = isABN
    ? `Remittance-${paymentDate.replace(/\//g, '-')}.pdf`
    : `Withholding-Statement-${paymentDate.replace(/\//g, '-')}.pdf`

  // Convert base64 string to Buffer for reliable Resend attachment handling
  let attachmentContent: Buffer
  try {
    attachmentContent = Buffer.from(pdfBase64, 'base64')
  } catch {
    return NextResponse.json({ error: 'Invalid PDF data' }, { status: 400 })
  }

  console.log(`[abn-payment] Sending ${paymentType} email to ${to}, attachment ${attachmentContent.length} bytes`)

  const { data, error } = await resend.emails.send({
    from: process.env.EMAIL_FROM ?? 'onboarding@resend.dev',
    to: [to],
    subject,
    html,
    attachments: [{
      filename,
      content: attachmentContent,
      contentType: 'application/pdf',
    }],
  })

  if (error) {
    Sentry.captureException(new Error((error as { message?: string }).message ?? 'Resend failed'), { tags: { feature: 'email_send', type: 'abn_payment' } })
    console.error('[abn-payment] Resend error:', JSON.stringify(error))
    return NextResponse.json({ error: (error as { message?: string }).message ?? 'Failed to send email' }, { status: 500 })
  }

  console.log('[abn-payment] Email sent successfully, id:', data?.id)
  return NextResponse.json({ ok: true, id: data?.id })
}
