-- TikTok video scripts generated by sparkGenerateTikTok().
-- Always status='draft' — never auto-published.

CREATE TABLE IF NOT EXISTS tiktok_scripts (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at  timestamptz DEFAULT now(),
  segment     text        NOT NULL,   -- tradies | intl_student_employer | payday_super_urgency
  hook        text        NOT NULL,   -- opening line (first 3 seconds)
  script_body text        NOT NULL,   -- full spoken script with stage directions
  cta         text        NOT NULL,   -- call to action at end
  status      text        DEFAULT 'draft'
);

ALTER TABLE tiktok_scripts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "No user access" ON tiktok_scripts;
CREATE POLICY "No user access" ON tiktok_scripts FOR ALL USING (false);

CREATE INDEX IF NOT EXISTS tiktok_scripts_status ON tiktok_scripts (status, created_at);
