-- Weekly referral report generated by Bridge agent.
-- One row per accountant-partner per week, tracking conversions and commission.
-- top_referrer is the accountant with the most conversions that week (denormalised for easy email rendering).

CREATE TABLE IF NOT EXISTS bridge_referral_reports (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at       timestamptz DEFAULT now(),
  week_starting    date        NOT NULL,
  accountant_email text        NOT NULL,
  referral_count   int         NOT NULL DEFAULT 0,
  commission_owed  numeric(8,2) NOT NULL DEFAULT 0,
  top_referrer     text
);

ALTER TABLE bridge_referral_reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "No user access" ON bridge_referral_reports;
CREATE POLICY "No user access" ON bridge_referral_reports FOR ALL USING (false);

CREATE INDEX IF NOT EXISTS bridge_referral_reports_week
  ON bridge_referral_reports (week_starting DESC, referral_count DESC);
