-- Community-targeted social media post drafts.
-- Generated by sparkPostCommunity() — always status='draft', never auto-published.

CREATE TABLE IF NOT EXISTS community_posts (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  segment    text        NOT NULL,   -- e.g. nepali_aus, indian_aus, tradies_aus
  platform   text        NOT NULL,   -- facebook | reddit | linkedin
  content    text        NOT NULL,
  status     text        DEFAULT 'draft'
);

ALTER TABLE community_posts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "No user access" ON community_posts;
CREATE POLICY "No user access" ON community_posts FOR ALL USING (false);

CREATE INDEX IF NOT EXISTS community_posts_status ON community_posts (status, created_at);
